# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"
# validate(config, schema="../schema/config_schema.yaml")

# load rules
# -----------------------------------------------------
include: "rules/00-Common.smk"
include: "rules/01-Alignment.smk"
include: "rules/02-Transcriptome_Assembly.smk"
# include: "rules/03-Sqanti3.smk"
include: "rules/03-Pigeon.smk"
include: "rules/04-ORF_Identification.smk"
include: "rules/05-Truncation.smk"
include: "rules/06-Evaluation.smk"

# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")

onsuccess:
    print("\n--- Workflow finished! ---\n")

onerror:
    print("\n--- An error occurred! ---\n")

# rule all:
#     input:
#         txt = transcriptome_path("StringTie_Sample_Assembly/gtf_list.txt"),
#         gtf2 = transcriptome_path("StringTie_Merge/merged_genome.gtf"),
#         clean_gtf = transcriptome_path("gffcompare/gffcompare.annotated.clean.gtf"),
#         ORFannotate_summary = orf_path("ORFannotate/pigeon.annotated/ORFannotate_summary.tsv"),
#         ORF_category = orf_path("ORF_Category/pigeon.annotated_orf.gtf"),
#         ORF_filtration = orf_path("ORF_Filtration/pigeon.annotated_orf.filter.gtf"),
#         truncated_3p_endome = truncation_path("gtxcutr/pigeon.annotated.gtxcutr.w500.3p.gtf"),
#         truncated_5p_endome = truncation_path("gtxcutr/pigeon.annotated.gtxcutr.w300.5p.gtf"),
#     default_target: True

DATASETS = ["Ebbert", "Wood"]
GROUPS = ["control_case", "control"]

# DATASETS = ["Ebbert"]
# GROUPS = ["control"]

TRUNCS = ["3p", "5p"]
WIDTHS = [300, 500]

rule all:
    input:
        endome_samples = expand(Path(results_output_path) / "{dataset}.{group}.endome_samples_df.tsv", dataset = DATASETS, group = GROUPS),
        gtf_list = expand(transcriptome_path("StringTie_Sample_Assembly/{dataset}.{group}.gtf_list.txt"), dataset = DATASETS, group = GROUPS),
        gffcompare_gtf = expand(transcriptome_path("gffcompare/{dataset}.{group}.gffcompare.annotated.clean.gtf"), dataset = DATASETS, group = GROUPS),
        pigeon_filter_gtf = expand(pigeon_path("Classify_Filter/{dataset}.{group}.pigeon.sorted.filtered.gtf"), dataset = DATASETS, group = GROUPS),
        orf_filtered_gtf = expand(orf_path("ORF_Filtration/{dataset}.{group}.orf_filter.gtf"), dataset = DATASETS, group = GROUPS),
        truncated_gtf = expand(truncation_path("gtxcutr/{dataset}.{group}.gtxcutr.w{width}.{txEnd}.gtf"), dataset = DATASETS, group = GROUPS, width = WIDTHS, txEnd = TRUNCS),
        kallisto_index = expand(evaluation_path("kallisto_index/{dataset}.{group}.gtxcutr.w{width}.{txEnd}.kdx"), dataset = DATASETS, group = GROUPS, width = WIDTHS, txEnd = TRUNCS),
        run_info = expand(evaluation_path("06-Evaluation/kallisto/{dataset}.{group}.w{width}.{txEnd}/{sample_id}/run_info.json"), dataset = DATASETS, group = GROUPS, width = WIDTHS, txEnd = TRUNCS, sample_id = evaluation_samples.index),
        # pigeon = expand(pigeon_path("Classify_Filter/{dataset}.{group}.pigeon_classification.txt"), dataset = DATASETS, group = GROUPS)
        # pigeon_filter_gtf = pigeon_path("Classify_Filter/pigeon.sorted.filtered.gtf"),
        # orf_filtered_gtf = orf_path("ORF_Filtration/pigeon_orf.filter.gtf"),
        # truncated_3p_gtf = truncation_path("gtxcutr/pigeon.gtxcutr.w500.3p.gtf"),
        # truncated_5p_gtf = truncation_path("gtxcutr/pigeon.gtxcutr.w300.5p.gtf"),
    default_target: True