[workspace]
authors = ["guillermo171996 <guillermorocamora@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "40-ENDome_generation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.23.0,<10"
conda = ">=26.5.3,<27"
