Ebbert.control.pc_custom.w500.3p:
  path: "debug_results/Ebbert.control/05-Truncation_3ad4/gtxcutr/"  # files must be relative to this
  genome: "hg38"
  gtf: "Ebbert.control.pc_custom.gtxcutr.w500.3p.gtf"
  kdx: "Ebbert.control.pc_custom.gtxcutr.w500.3p.kdx"
  merge_tsv: "Ebbert.control.pc_custom.gtxcutr.w500.3p.merge.tsv"
  tx_annots: null
  tx_annots_csv: null
  gene_annots: null
  gene_annots_csv: null